<title>TaMCh Inc. | Sign up</title>

  <body class="login-img3-body">

    <div class="container">

      <form class="login-form" method="post" action="/index/register">        
        <div class="login-wrap">
            <p class="login-img"><i class="icon_lock_alt"></i></p>
            <div class="input-group">
              <span class="input-group-addon"><i class="icon_profile"></i></span>
              <input type="text" class="form-control" name="username" placeholder="Username" autofocus>
            </div>
            <div class="input-group">
                <span class="input-group-addon"><i class="icon_key_alt"></i></span>
                <input type="password" class="form-control" name="password" placeholder="Password">
            </div>
	    <div class="input-group">
              <span class="input-group-addon"><i class="icon_profile"></i></span>
              <input type="text" class="form-control" name="first_name" placeholder="First name" autofocus>
            </div>
	    <div class="input-group">
              <span class="input-group-addon"><i class="icon_profile"></i></span>
              <input type="text" class="form-control" name="last_name" placeholder="Last name" autofocus>
            </div>
	    <div class="input-group">
              <span class="input-group-addon"><i class="icon_mail"></i></span>
              <input type="text" class="form-control" name="email" placeholder="Email" autofocus>
            </div>
            <button class="btn btn-info btn-lg btn-block"  formmethod="post" type="submit" formaction="/index/register">Signup</button>
        </div>
      </form>

    </div>


  </body>
</html>